### ISSUE TITLE
数据集有问题

### ISSUE THREAD

**Issue by xulangping** [Samurais/insuranceqa-corpus-zh#10]
老哥，你把正例负例搞成1:10，真是太荒谬了，这样跑出来的结果不管正例还是负例，都是判错，导致最后准确率极限是10/11.应该选取符合实际情况的数据集，这样才有说服力。

**Comment by Samurais** [comment]
1) 这个数据集是基于 [insuranceQA](https://github.com/shuzi/insuranceQA) 的。
2) 这个数据集是用来学习和研究的，可以不局限于实际情况。
3) 数据集的正负例的搭配情况可以根据用户的算法自己选择。比如在训练神经网络时，可以让负例随机选择而且尽可能的多。

我在给出的示例程序中，[evaluate](https://github.com/Samurais/insuranceqa-corpus-zh/blob/release/deep_qa_1/network.py#L142)中关于精度的计算，以及[InsuranceQA_zh](https://github.com/l11x0m7/InsuranceQA_zh/blob/master/train.py#L141)中使用混淆矩阵做评测可作为具体的办法。

所以，你的结论不正确。
