### ISSUE TITLE
增加基线模型和数据

### ISSUE THREAD

**Issue by Samurais** [Samurais/insuranceqa-corpus-zh#2]
Good news!
# 增加baseline model

一个使用insuranceqa-corpus-zh语料库训练问答模型的深度学习网络

- [程序和结果](https://github.com/Samurais/insuranceqa-corpus-zh#基线)

 @fssqawj
@rgtjf
@sjqzhang
@Samurais
@shibing624
@sizhen
@ax4
@park
@songzi1229
@AdolHong
@bcao
@robotdj
@Allensmile
@behonests
@playniuniu
@xuansage
@zixia
@LucasHood001
@madfrog2047
@greatgeekgrace
@aliray

**Comment by rgtjf** [comment]
Excellent work! @Samurais

能不能简单说明一下baseline model， 比如说(Logistic Regression )，
以及在dev和test上的结果。

**Comment by Samurais** [comment]
Baseline model 的介绍文章在这里 [https://github.com/Samurais/insuranceqa-corpus-zh/blob/release/deep_qa_1/baseline_article.pdf](https://github.com/Samurais/insuranceqa-corpus-zh/blob/release/deep_qa_1/baseline_article.pdf)
