### ISSUE TITLE
回答结果如何输出

### ISSUE THREAD

**Issue by Juary88** [Samurais/insuranceqa-corpus-zh#7]
如何输出结果

**Comment by Samurais** [comment]
参考 https://github.com/Samurais/insuranceqa-corpus-zh/blob/release/deep_qa_1/network.py#L142

**Comment by Samurais** [comment]
例如：

```
    def predict(self, text, seg = True):
        '''
        predict a text
        '''
        v = corpus.v(text, seg = seg)
        if len(v) > 0:
            return np.argmax(self.feedforward(np.reshape(v, (self.input_layer_size, 1))))
        else:
            return 1
```

就是将输入的query转化成向量，再做前向网络的计算。

**Comment by dengqiqi123** [comment]
不明白是怎么做问答输出的？predict预测出来是0 和 1

**Comment by MrRace** [comment]
> 例如：
> 
> ```
>     def predict(self, text, seg = True):
>         '''
>         predict a text
>         '''
>         v = corpus.v(text, seg = seg)
>         if len(v) > 0:
>             return np.argmax(self.feedforward(np.reshape(v, (self.input_layer_size, 1))))
>         else:
>             return 1
> ```
> 就是将输入的query转化成向量，再做前向网络的计算。

这里的text是指原始的问句吧，然后你这里仅仅示意分词和矢量化。请问对于一个新输入的问句此时构建input也是需要添加<GO>吗？或者是直接只要PAD就可以？

**Comment by Sunwc0** [comment]
这就是个文本分类的网络把，输出救俩类
